// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW6ObbNIK2qifoyNS8pbn3jzY9w4LyLHg',
    appId: '1:689915768125:web:4e780a28fd21897d0be954',
    messagingSenderId: '689915768125',
    projectId: 'shopping-cart-e5b7a',
    authDomain: 'shopping-cart-e5b7a.firebaseapp.com',
    storageBucket: 'shopping-cart-e5b7a.firebasestorage.app',
    measurementId: 'G-EBH0BZHZ05',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBArqrpiq6_Gt2M44m8hdq6eFm4Anfn9so',
    appId: '1:689915768125:android:4d0d7e83820991730be954',
    messagingSenderId: '689915768125',
    projectId: 'shopping-cart-e5b7a',
    storageBucket: 'shopping-cart-e5b7a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDttp1dZ3E5TdjA8gvq0TnV2NYaoDXa7oA',
    appId: '1:689915768125:ios:555707555c9657780be954',
    messagingSenderId: '689915768125',
    projectId: 'shopping-cart-e5b7a',
    storageBucket: 'shopping-cart-e5b7a.firebasestorage.app',
    iosBundleId: 'com.example.shoppingCart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDttp1dZ3E5TdjA8gvq0TnV2NYaoDXa7oA',
    appId: '1:689915768125:ios:555707555c9657780be954',
    messagingSenderId: '689915768125',
    projectId: 'shopping-cart-e5b7a',
    storageBucket: 'shopping-cart-e5b7a.firebasestorage.app',
    iosBundleId: 'com.example.shoppingCart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDW6ObbNIK2qifoyNS8pbn3jzY9w4LyLHg',
    appId: '1:689915768125:web:f214d0b7bf1e128b0be954',
    messagingSenderId: '689915768125',
    projectId: 'shopping-cart-e5b7a',
    authDomain: 'shopping-cart-e5b7a.firebaseapp.com',
    storageBucket: 'shopping-cart-e5b7a.firebasestorage.app',
    measurementId: 'G-EERNFSGXGM',
  );
}
